region_photo_dict = {
// Cuba
'Havana': [
  ['Havana-1', 'A Women Selling Coffee in Old Havana'],
  ['Havana-2', 'Plaza de la Revolution'],
  ['Havana-3', 'The Malecon'],
  ['Havana-4', 'A Local Store in Old Havana'],
  ['Havana-5', 'An Elementary school'],
  ['Havana-6', "School Girls"],
  ['Havana-7', "Hay Ron (We've got Rum)."],
  ['Havana-8', 'A Man in the Red Car'],
  ['Havana-9', 'A Bar in Old Havana'],
  ['Havana-10', 'Fidel']],
'Trinidad': [
  ['Trinidad-1', 'Trinidada at Sunset'],
  ['Trinidad-2', 'Trinidada at Early Morning'],
  ['Trinidad-3', 'Taxi'],
  ['Trinidad-4','Crosses and Colorful Houses'],
  ['Trinidad-5','Carriage'],
  ['Santa Clara-1','Che Guevara, Santa Clara']],
// Easter Island
'Easter Island 1':[
  ['Easter Island-1', 'Rano Kau'],
  ['Easter Island-2', 'Fallen Moais'],
  ['Easter Island-3','Fallen Moais'],
  ['Easter Island-4', 'Ahu Nau Nau and the Pacific Ocean'],
  ['Easter Island-5', 'Ahu Nau Nau and Pine Trees'],
  ['Easter Island-6', 'Ahu Te Pito Kura, the Tallest Moai']],
'Easter Island 2': [
  ['Easter Island-7', 'Ahu Te Pito Kura'],
  ['Easter Island-8', 'Ahu Tongariki at Sunrise'],
  ['Easter Island-9', 'Ahu Tongariki'],
  ['Easter Island-10', 'Ahu Tongariki'],
  ['Easter Island-11', 'Rano Raraku'],
  ['Easter Island-12', 'Tahai at Sunset']],
// Patagonia
'Perito Moreno Glacier': [
  ['Perito Moreno Glacier-1', 'Glacier'],
  ['Perito Moreno Glacier-2', 'Glacier'],
  ['Perito Moreno Glacier-3', 'Glacier'],
  ['Perito Moreno Glacier-4', 'Glacier'],
  ['Perito Moreno Glacier-5', 'Glacier']],
'El Chalten': [
  ['El Chalten-1', 'Fitz Roy and Cerro Torre'],
  ['El Chalten-2', 'Fitz Roy and Hidden Falls'],
  ['El Chalten-3', 'Fitz Roy at Sunrise'],
  ['El Chalten-4', 'Fitz Roy Reflection'],
  ['El Chalten-5', 'Fitz Roy and Laguna de los Tres'],
  ['El Chalten-6', 'Rio de las Vueltas'],
  ['El Chalten-7', 'Cerro Torre'],
  ['El Chalten-8', 'Cerro Torre and Laguna Torre']],
// Mexico
'San Miguel de Allende': [
  ['San Miguel-1', 'San Miguel de Allende'],
  ['San Miguel-2', 'Two Walkers'],
  ['San Miguel-3', 'Parroquia de San Miguel Arcángel at Sunset'],
  ['San Miguel-4', 'Ballons'],
  ['Guanajuato-1', 'A Gas Station in Guanajuato'],
  ['Guanajuato-2', 'Ninos en Guanajuato'],
  ['Guanajuato-3', 'Guanajuato at Sunset']],
'Puerto Vallarta': [
  ['Puerto Vallarta-1', 'Lavanderia'],
  ['Puerto Vallarta-2', 'Iglesia de Nuestra Senora de Guadalupe'],
  ['Puerto Vallarta-3', 'Iglesia de Nuestra Senora de Guadalupe'],
  ['Puerto Vallarta-4', 'Fiesta'],
  ['Puerto Vallarta-5', 'Tapas Bar']],
// USA
'Arizona': [
  ['Arizona-1', 'Scottsdale at Sunset'],
  ['Arizona-2', 'Scottsdale'],
  ['Arizona-3', 'Antelope Canyon'],
  ['Arizona-4', 'Antelope Canyon'],
  ['Arizona-5', 'Horseshoe Bend at Sunrise'],
  ['Arizona-6', 'Antelope Canyon'],
  ['Arizona-7', 'Grand Canyon'],
  ['Arizona-8', 'Grand Canyon'],
  ['Arizona-9', 'Sedona'],
  ['Arizona-10', 'Sedona']],
'California': [
  ['California-1', 'Morro Bay'],
  ['California-2', 'La Jolla'],
  ['California-3', 'La Jolla'],
  ['California-4', 'Napa Valley'],
  ['California-5', 'Golden Gate Bridge'],
  ['California-6', 'Death Valley'],
  ['California-7', 'Death Valley'],
  ['California-8', 'Death Valley']],
'Oregon and Washington': [
  ['Oregon-1', 'Willamette Valley'],
  ['Oregon-2', 'Columbia River Gorge'],
  ['Washington-1', "Seattle, the Original Sturbuck's Coffee"]],
'Minnesota': [
  ['Minnesota-1', 'Fall Colors'],
  ['Minnesota-2', 'Fall Colors'],
  ['Minnesota-3', 'Frozen Minehaha Falls'],
  ['Minnesota-4', 'April Snow'],
  ['Minnesota-5', 'Canoes'],
  ['Minnesota-6', 'Brocken Spectre on Lake Superior'],
  ['Minnesota-7', 'Lake Superior'],
  ['Minnesota-8', 'Fall Colors']],
//'New York': [],
'Hawaii': [
  ['Hawaii-1', 'Lanikai Beach, Oahu'],
  ['Hawaii-2', 'Makawao, Maui'],
  ['Hawaii-3', 'North Shore, Oahu'],
  ['Hawaii-4', 'Pill Box Trail, Oahu'],
  ['Hawaii-5', 'Coffee Plantation, Big Island'],
  ['Hawaii-6', 'Mauna Kea Observatories, Big Island'],
  ['Hawaii-7', 'Lanai'],
  ['Hawaii-8', 'Mauna Kea, Big Island'],
  ['Hawaii-9', 'Maili Pill Box Trail, Oahu'],
  ['Hawaii-10', 'Pill Box Trail, Oahu']],
// France
//'Paris': ['Rome 1','Rome 2','Rome 3'],
'Alsace': [
  ['Alsace-1', 'Eguisheim'],
  ['Alsace-2', 'Hunawihr, Fall'],
  ['Alsace-3', 'Hunawihr'],
  ['Alsace-4', 'Hunawihr, Summer'],
  ['Alsace-5', 'Christmass Market, Kaysersberg'],
  ['Alsace-6', 'Christmass Market, Kaysersberg'],
  ['Alsace-7', 'Christmass Market, Ribeauville'],
  ['Alsace-8', 'Hunawihr, Winter'],
  ['Alsace-9', 'Eguisheim'],
  ['Alsace-10', 'Strausbourg']],
'Bordeaux': [
  ['Bordeaux-1', 'Arcachon, Oyster Hut'],
  ['Bordeaux-2', 'Arcachon, Oyster Hut'],
  ['Bordeaux-3', 'St Emilion'],
  ['Bordeaux-4', 'St Emilion'],
  ['Bordeaux-5', 'Vinyard in St Emilion'],
  ['Bordeaux-6', 'Vinyard in St Emilion'],
  ['Bordeaux-7', 'Fishing Hut in Gironde Estuary'],
  ['Bordeaux-8', "Cos d'Estournel, St Estephe"],
  ['Bordeaux-9', ' ']],
'Aveyron': [
  ['Aveyron-1', 'Congues'],
  ['Aveyron-2', 'Congues'],
  ['Aveyron-3', 'Congues'],
  ['Aveyron-4', 'Congues'],
  ['Aveyron-5', 'Estaing'],
  ['Aveyron-6', 'Estaing'],
  ['Aveyron-7', 'Estaing']],
'Normandie': [
  ['Normandie-1', 'Honfleur'],
  ['Normandie-2', 'Saint-Malo'],
  ['Normandie-3', 'Trouville'],
  ['Normandie-4', 'Mont-Saint-Michel'],
  ['Normandie-5', 'Mont-Saint-Michel'],
  ['Normandie-6', 'Mont-Saint-Michel']],
'Provence': [
  ['Provence-1', "L'Isle-sur-la-Sorgue"],
  ['Provence-2', "L'Isle-sur-la-Sorgue"],
  ['Provence-3', 'Roussillon'],
  ['Provence-4', 'Roussillon'],
  ['Provence-5', 'Gordes'],
  ['Provence-6', 'Gordes'],
  ['Provence-7', 'Abbaye Notre-Dame de Sénanque'],
  ['Provence-8', 'Saint-Remy'],
  ['Provence-9', 'Arles']],
'Rhone': [
  ['Rhone-1', 'Hill Top Chapel in Hermitage'],
  ['Rhone-2', 'Tournon-sur-Rhone'],
  ['Rhone-3', 'Hill Top Chapel in Hermitage'],
  ['Rhone-4', 'Albertville'],
  ['Rhone-5', 'Albertville'],
  ['Rhone-6', 'Col de la Madeleine']],
'Basque': [
  ['Spanish Basque-1', 'Hondarribia'],
  ['Spanish Basque-2', 'Hondarribia'],
  ['Spanish Basque-3', 'Hondarribia'],
  ['Spanish Basque-4', 'Bera'],
  ['Spanish Basque-5', 'San Sebastian'],
  ['Spanish Basque-6', 'San Sebastian'],
  ['French Basque-1', 'Espelette'],
  ['French Basque-2', 'Espelette'],
  ['French Basque-3', 'Espelette'],
  ['French Basque-4', 'A Farm House'],
  ['French Basque-5', 'Ainhoa'],
  ['French Basque-6', 'Ainhoa']],
// Italy
'Florence and Siena': [
  ['Florence-1', 'Firenze'],
  ['Florence-2', 'Firenze'],
  ['Siena-1', 'Siena'],
  ['Siena-2', 'Siena'],
  ['San Gimignano-1', 'San Gimignano'],
  ['San Gimignano-2', 'San Gimignano'],
  ['San Gimignano-3', 'San Gimignano']],
"Val d'Orcha 1": [
  ["Val d'Orcha-1", 'Pienza at Sunrise'],
  ["Val d'Orcha-2", "Val d'Orcha with Sea of Clouds"],
  ["Val d'Orcha-3", 'Pienza at Sunrise'],
  ["Val d'Orcha-4", "A Chapel in Val d'Orcha"],
  ["Val d'Orcha-5", 'Montalcino'],
  ["Val d'Orcha-6", "Val d'Orcha with Poppy Flower"]],
"Val d'Orcha 2": [
  ["Val d'Orcha-7", "Val d'Orcha at Dawn"],
  ["Val d'Orcha-8", 'Pienza at Sunrise'],
  ["Val d'Orcha-9", "Val d'Orcha, at Sunrise"],
  ["Val d'Orcha-10", "San Quirico d'Orcia"],
  ["Val d'Orcha-11", 'Winding Road Lined with Cypress, Monticchiello'],
  ["Val d'Orcha-12", 'Winding Road Lined with Cypress, Asciano'],
  ["Val d'Orcha-13", 'Montepulciano']],
'Maremma': [
  ['Sorano-1', 'Sorano'],
  ['Sorano-2', 'Sorano'],
  ['Sovana-1', 'Sovana'],
  ['Sovana-2', 'Sovana'],
  ['Pitigliano-1', 'Pitigliano'],
  ['Pitigliano-2', 'Pitigliano'],
  ['Montemerano-1', 'Montemerano'],
  ['Montemerano-2', 'Montemerano'],
  ['Montemerano-3', 'Montemerano'],
  ['Montemerano-4', 'Montemerano']],
'Civita and Orvieto': [
  ['Civita-1', 'Civita'],
  ['Civita-2', 'Civita at Sunset'],
  ['Civita-3', 'Civita at Sunrise'],
  ['Civita-4', 'Civita at Sunrise'],
  ['Civita-5', 'Civita'],
  ['Civita-6', 'Infiorata, Lubriano'],
  ['Civita-7', 'Infiorata, Lubriano'],
  ['Orvieto-1', 'Orvieto'],
  ['Orvieto-2', 'Orvieto'],
  ['Orvieto-3', 'Orvieto'],
  ['Orvieto-4', 'Orvieto'],
  ['Orvieto-5', 'Orvieto at Sunset']],
'Rome': [
  ['Rome-1', 'Rome at Sunset'],
  ['Rome-2', 'Basilica di San Pietro at Sunset'],
  ['Rome-3', 'Colosseo'],
  ['Rome-4', 'Piazza del Popolo'],
  ['Rome-5', 'Foro Romano at Sunrise']],
//'Milan and Como': [] 'Ravenna': [],'Naples': [], 'Positano': [],
// Spain (Basque in France)
'Andalucia': [
  ['Andalucia-1', 'Sunflowers'],
  ['Andalucia-2', 'Zahara de la Sierra'],
  ['Andalucia-3', 'Ronda'],
  ['Andalucia-4', 'Casares'],
  ['Andalucia-5', 'La Alhambra, Granada'],
  ['Andalucia-6', 'La Alhambra, Granada']],
'Barcelona': [
  ['Barcelona-1', 'Hospital de Sant Paul'],
  ['Barcelona-2', 'La Sagrada Família'],
  ['Barcelona-3', 'La Sagrada Família']],
// Other Countries
'Croatia 1': [
  ['Croatia-1', 'Dubrovnik'],
  ['Croatia-2', 'Dubrovnik'],
  ['Croatia-3', 'Dubrovnik'],
  ['Croatia-4', 'Dubrovnik'],
  ['Croatia-5', 'Dubrovnik']],
'Croatia 2': [
  ['Croatia-6', 'Dubrovnik'],
  ['Croatia-7', 'Dubrovnik'],
  ['Croatia-8', 'Dubrovnik'],
  ['Croatia-9', 'Zagreb'],
  ['Croatia-10', 'Zagreb']],
'Montenegro': [
  ['Montenegro-1', 'Kotor'],
  ['Montenegro-2', 'Sveti Stefan']],
'Czech': [
  ['Czech-1', 'The Palace, Prague'],
  ['Czech-2', 'Prague'],
  ['Czech-3', 'Prague'],
  ['Czech-4', 'Prague'],
  ['Czech-5', 'Charles Bridge, Prague'],
  ['Czech-6', 'Prague'],
  ['Czech-7', 'Telc'],
  ['Czech-8', 'Telc'],
  ['Czech-9', 'Cesky Krumlov']],
'Ireland': [
  ['Ireland-1', 'Temple Bar, Dublin'],
  ['Ireland-2', ' '],
  ['Ireland-3', 'Cliffs of Moher at Sunset'],
  ['Ireland-4', 'Inishmore (Aran Island)'],
  ['Ireland-5', 'Inishmore (Aran Island)'],
  ['Ireland-6', 'Sligo'],
  ['Ireland-7', 'Dunluce Castle'],
  ['Ireland-8', "Giant's Causeway"],
  ['Ireland-9', "Giant's Causeway"]],
'Scotland': [
  ['Scotland-1', 'Dunnottar Castle'],
  ['Scotland-2', 'Whisky Distillery'],
  ['Scotland-3', 'Highland Cattle']],
'Norway': [
  ['Norway-1', 'Myrdal to Flam Hike'],
  ['Norway-2', 'Myrdal to Flam Hike'],
  ['Norway-3', 'Myrdal to Flam Hike'],
  ['Norway-4', 'Myrdal to Flam Hike'],
  ['Norway-5', 'Myrdal to Flam Hike'],
  ['Norway-6', 'Flam'],
  ['Norway-7', 'Flam'],
  ['Norway-8', 'Bergen']],
'Greece': [
  ['Greece-1', 'Santorini'],
  ['Greece-2', 'Santorini'],
  ['Greece-3', 'Santorini'],
  ['Greece-4', 'Crete'],
  ['Greece-5', 'Crete']],
'Portugal': [
  ['Portugal-1', 'Jeronimos Monastry, Lisbon'],
  ['Portugal-2', 'Estremoz'],
  ['Portugal-3', 'Porto'],
  ['Portugal-4', 'Estremoz'],
  ['Portugal-5', 'Cork Havest, Alentejo'],
  ['Portugal-6', 'Evora'],
  ['Portugal-7', 'Monsaraz'],
  ['Portugal-8', 'Marvao']],
'Thailand': [
  ['Thailand-1', 'Ayutthaya'],
  ['Thailand-2', 'Bangkok'],
  ['Thailand-3', 'A Praying Woman, Bangkok'],
  ['Thailand-4', 'Wat Arun at Sunset'],
  ['Thailand-5', 'Wat Arun at Dusk'],
  ['Thailand-6', 'Flower Market'],
  ['Thailand-7', 'Flower Market']]
}

var urlHash = location.hash.slice(1) // obtain keyword from url hash
urlHash = urlHash.replace('%20', ' ') // remove %20 for space (in case multiple)
urlHash = urlHash.replace('%20', ' ')
urlHash = urlHash.replace('%20', ' ')
urlHash = urlHash.replace('%20', ' ')
photo_list = region_photo_dict[urlHash]

// create HTML for <div id=page_description>
var div = document.getElementById('page_description')
var h3 = document.createElement('H3')
h3.textContent = 'Photo Gallery of ' + urlHash
div.appendChild(h3)
